[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dynaconf>=3.2.10",
    "loguru>=0.7.3",
    "numpy>=2.2.5",
    "pillow>=11.2.1",
    "s3fs>=2025.3.2",
]
