[db]
user = "hackupc"
password = "eyKUUk0fLdMlSJUvJp9KHxMHlp0EcF4T"
host = "dpg-d0akue6r433s73f1e6o0-a.frankfurt-postgres.render.com"
port = 5432
name = "postgres_hackupc"

[minio]
access_key = "hackupc"
secret_key = "hackupc123"