[s3]
storage_url ="https://minio:9005"
bucket_name = "hackupc"
folder = "images"
result_folder = "results"

[frontend]
url = "https://frontend-9k9u.onrender.com"

[mlserver]
host = "mlserver"
port = 8050
batch_size = 2
