[s3]
storage_url ="http://minio:9005"
bucket_name = "hackupc"
folder = "images"
result_folder = "results"

[frontend]
url = "https://743b-147-83-201-128.ngrok-free.app"

[mlserver]
host = "mlserver"
port = 8050
batch_size = 2
