[s3]
storage_url ="http://minio:9005"
bucket_name = "hackupc"
folder = "images"
result_folder = "results"

[frontend]
url = "https://hackconnect.lamelas24.com"

[mlserver]
host = "mlserver"
port = 8050
batch_size = 2


[logging]
level = "DEBUG"
